### ISSUE TITLE
No module named 'imp'

### ISSUE THREAD

**Issue by janekbii** [salilab/imp#1013] opened 2019-02-07 02:59 UTC
Trying to use:
$emagefit
and I get the error:

Traceback (most recent call last):
  File "/usr/bin/emagefit", line 14, in <module>
    import IMP
ModuleNotFoundError: No module named 'IMP'

Ubuntu 16.04, any help appreciated

**Comment by benmwebb** [comment] 2019-02-07 05:27
What version of IMP, and how did you install it? What is the output of `which python`?

**Comment by janekbii** [comment] 2019-02-07 05:33
I followed the: https://integrativemodeling.org/download-linux.html

then:
$sudo apt-get install imp-python3

On the: Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux

**Comment by benmwebb** [comment] 2019-02-07 05:40
OK, your problem is that you installed the Ubuntu package, which is designed to work with Ubuntu's Python (`/usr/bin/python` or `/usr/bin/python3`) but you are using Anaconda Python instead. The easiest way to make this work would be to install IMP for Anaconda Python, as per https://integrativemodeling.org/download-anaconda.html. You would need to upgrade your Anaconda to the latest release though (Python 3.7).

**Comment by janekbii** [comment] 2019-02-07 05:45
Thanks. Would it be easier to use IMP for python2 (which I have also installed on my ubuntu /usr/bin/python2)? I tried installing IMP for python2 but got the same error. Where can I change it so that IMP will be using python2 as default (it is not at the moment).

**Comment by benmwebb** [comment] 2019-02-07 05:50
The issue is that Anaconda Python is first in your `PATH`. If you remove the Anaconda Python location from your `PATH` so that running `python` gives you Ubuntu's Python in `/usr/bin`, then IMP will work.

**Comment by janekbii** [comment] 2019-02-07 06:06
I did not have anaconda specified in my .bashrc or .bash_profile, rather:

export PATH="/home/marzinekj/miniconda3/bin:$PATH"

Also I made sure python with execute:
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.

Tried these and reinstalled the IMP for python2 but still does not work

**Comment by benmwebb** [comment] 2019-02-07 06:10
Right, so you had Anaconda in your default `PATH` and you (presumably) removed it. Now, what happens if you run `python` from the command line and then `import IMP` in that Python session?

But "still does not work" do you mean you still see the original error? If so, then something is still wrong with your `PATH` for Python because that is a Python 3-specific error and you should be running Python 2 now.

**Comment by janekbii** [comment] 2019-02-07 06:22
`import IMP`
gives:
import: not authorized `IMP' @ error/constitute.c/WriteImage/1028.

**Comment by benmwebb** [comment] 2019-02-07 06:24
You need to run this at Python's `>>>` prompt, not in the shell.

**Comment by janekbii** [comment] 2019-02-07 06:32
It does work without errs. But I am still getting the:
Traceback (most recent call last):
File "/usr/bin/emagefit", line 14, in
import IMP
ModuleNotFoundError: No module named 'IMP'

when trying to use $emagefit

**Comment by benmwebb** [comment] 2019-02-07 06:38
>  ModuleNotFoundError: No module named 'IMP'

As I said already, this is a Python 3-specific error, so you must still have an issue with your `PATH`.

**Comment by benmwebb** [comment] 2019-02-07 22:01
Another workaround you can try if you can't fix your `PATH` is to edit `/usr/bin/emagefit` and change the first line from `#!/usr/bin/env python` to `#!/usr/bin/python2` to force it to use Ubuntu's Python.

**Comment by benmwebb** [comment] 2019-06-26 16:11
I assume this is fixed in the current release. If not, reopen.

**Closed by benmwebb** 2019-06-26 16:11 UTC

**Comment by hfxben** [comment] 2023-11-03 17:28
It still rot on windows python3!

**Comment by benmwebb** [comment] 2023-11-03 17:35
> It still rot on windows python3!

@hfxben If you have a problem, please open a new issue and describe what the problem is, don't comment on a long-closed unrelated issue (this relates to Ubuntu, sounds like you might be using Windows). And obviously we will need more detail to help you - no idea what "rot on windows" means, sorry.
