### ISSUE TITLE
CGAL deprecated headers warning

### ISSUE THREAD

**Issue by barakr** [salilab/imp#955] opened 2016-07-20 21:09 UTC
I get the following deprecation warning on the CGAL library - I guess it's not urgent but I wasn't sure how to trivially fix it cause they seem to have switched the actual interface:

=====
include/CGAL/internal/deprecation_warning.h:57:6: warning: #warning "A deprecated header has been included." [-Wcpp]
 #    warning "A deprecated header has been included."
      ^
In file included from /usr/include/CGAL/Regular_complex_d.h:33:0,
                 from /usr/include/CGAL/Convex_hull_d.h:78,
                 from /piri1/home/barak/imp_git/repository/modules/cgal/src/internal/sphere_cover.cpp:20,
                 from src/cgal_all.cpp:9:
/usr/include/CGAL/internal/deprecation_warning.h:57:6: warning: #warning "A deprecated header has been included." [-Wcpp]
 #    warning "A deprecated header has been included."
      ^
In file included from /usr/include/CGAL/Convex_hull_d.h:33:0,
                 from /piri1/home/barak/imp_git/repository/modules/cgal/src/internal/sphere_cover.cpp:20,
                 from src/cgal_all.cpp:9:
====

**Comment by benmwebb** [comment] 2016-07-21 10:35
Duplicate of #904

**Closed by benmwebb** 2016-07-21 10:35 UTC
Labels: warning
